#!/usr/bin/python3
import os 
from tapyr.api import Tapir
import json

def recurse(node):
  for child_info in node.children:
    child = session.node_by_id(child_info.id)
    recurse(child) 
    res = session.schedule("clamav", {"file" : child_info.id})

session = Tapir()

root = session.node('/root')
recurse(root)
