#!/usr/bin/python3
import sys
sys.path.append('../tapyr')

import os 
from tapyr import Tapir

address = os.getenv('ADDRESS')
if address== None:
  address = "127.0.0.1:3583"

session = Tapir(*address.split(":"))
root = session.node("/root")

res = session.run("device", {"path" : sys.argv[1], "mount_point" : root.id })
