#!/usr/bin/python3
import sys
import os 
from tapyr.api import Tapir

if len(sys.argv) != 2:
  print(sys.argv[0] + " [DEVICE_PATH]")
else:
  session = Tapir()
  root = session.node("/root")
  res = session.run("device", {"path" : sys.argv[1], "mount_point" : root.id })
