#!/usr/bin/python3
import sys
sys.path.append('../tapyr')

import os 
from tapyr import Tapir

address = os.getenv('ADDRESS')
if address== None:
  address = "127.0.0.1:3583"
session = Tapir(*address.split(":"))

node = session.node(sys.argv[1])

name = sys.argv[1].rsplit('/')[-1]
try: 
  name = sys.argv[2]
except:
  pass

#XXX don't use download for large file
#as all file is buffered before return
#use rather cat
b = session.download(node.id, name)
