#!/usr/bin/python3
import sys
sys.path.append('../tapyr')

import os
from tapyr import Tapir


def usage():
  print("./" + sys.argv[1] + " [PATH]")

def list_children(path, size):
  node = session.node(path)
  try:
    data_size = node.data.size
    size += data_size
  except:
    pass
  try:
    for node in node.children:
      child_path = path + "/" + node.name
      size = list_children(child_path, size)
  except:
    pass
  return size

argc = len(sys.argv)

if argc == 1:
  session = Tapir()
  size = list_children("/root", 0)
  print(size)
elif argc == 2:
  session = Tapir()
  size = list_children(sys.argv[1], 0)
  print(size)
else:
    usage()
