#!/usr/bin/python3
import sys
import os
from tapyr import Tapir

if len(sys.argv) != 2:
  print(sys.argv[0] + " [FILE_PATH]")
else:
  session = Tapir()
  node = session.node(sys.argv[1])
  res = session.run("partition", { "file" : node.id })
