#!/usr/bin/python3
import sys
sys.path.append('../tapyr')

import os
from tapyr import Tapir

session = Tapir()

for plugin in session.plugins():
  print(plugin["name"], "\t\t:", plugin["description"])
