#!/usr/bin/python3
import sys
sys.path.append('../tapyr')

import os 
from tapyr import Tapir
import json

address = os.getenv('ADDRESS')
if address== None:
  address = "127.0.0.1:3583"
session = Tapir(*address.split(":"))

path = sys.argv[1]
if path[-1] == "/":
  path = path[:-1]
res = session.run("local", {"files" : [path], "mount_point" : root.id }) #, timeout = 1000)

registry_node = session.node(sys.argv[1])
res = session.run("registry", {"data_path" : registry_node.id})


